### PR TITLE
Added v0.0.2 dat tests

### PR DESCRIPTION
**Pull request by JHibbard**
This pull request adds dat v0.0.2 tests to deltaray.

### CODE REVIEW

**Comment by MrPowers** [comment]
I think we should loop through all the reference tables and programmatically run the tests, similar to [this commit](https://github.com/delta-io/delta-rs/commit/b67c602a02dd76d96de500163da490a5abd949d3).

**Comment by JHibbard** [comment]
Good idea, but we don't currently need all of the reference tables to test deltaray. A good next step could be a list of reference tables that are relevant and a test fixture that loops over that list with the default being all tables.

**Comment by MrPowers** [comment]
That seems like a reasonable suggestion.  Feel free to skip the tables that aren't relevant, perhaps with a comment on why the table isn't relevant.

**Comment by JHibbard** [comment]
I like that idea, I'll merge this but create a roadmap/docs to add that context.

**Comment by JHibbard** [comment]
Opened up [PR#11](https://github.com/delta-incubator/deltaray/pull/11) that references this PR and better reflects the proposed inclusion of DAT in `deltaray`. It outlines the current subset of DAT test cases we'd intend to use in the near term and better motivates DAT's inclusion within the testing framework. Thanks!

**Pull request merged**
